"""Advent of Code 2025: Day 6 - Trash Compactor"""

from advent import parse, atoms, operator, reduce, compose


def apply(op_sym: str, args: list[int]) -> int:
    """Apply an operator to a list of arguments. For example, apply('+', [1,2,3]) returns 6."""
    return reduce({'+': operator.add, '-': operator.sub, '*': operator.mul}[op_sym], args)


def part1() -> int:
    """
    1. Parse the input into rows
    2. Transpose rows to columns using zip(*rows)
    3. Sum the result of applying the operator to the args for each column"""
    return sum([apply(col[-1], col[:-1]) for col in zip(*parse(6, atoms))])


def part2() -> int:
    """
    1. Transform our input so columns become rows after reversing each line, and
    forming the transpose. Then filter out any rows containing only spaces:
    [[ '1', '2', '3', ' ', ' ', '6' ],     [[ '6', '8', ' '],
     [ '4', '5', ' ', ' ', '7', '8' ], -->  [ ' ', '7', '*'], 68 * 7
     [ '+', ' ', ' ', ' ', '*', ' ' ]]      [ '3', ' ', ' '],
                                            [ '2', '5', ' '],
                                            [ '1', '4', '+']] 3 + 25 + 14
    2. Return the sum of all answers generated by our helper function.
    """
    rows = filter(
        lambda row: ''.join(row).strip(),
        zip(*parse(6, compose(reversed, list), do_rstrip=False)),
    )

    def answers(rows):
        """Accumulate an int argument from each row, until a row ends with an operator, then apply
        the operator to the accumulated args, yield the answer, clear the arg list, and repeat."""
        args = []

        for row in rows:
            args.append(int(''.join(row[:-1]).strip()))

            if row[-1] in ['+', '-', '*']:
                yield apply(row[-1], args)
                args = []

    return sum(answers(rows))


assert part1() == 3525371263915
assert part2() == 6846480843636
